version: '3.4'

services:
  cassandra-1:
    image: cassandra:latest
    container_name: cassandra-1
    restart: on-failure
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_SEEDS=cassandra-1, cassandra-2, cassandra-3
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - ${DATA}/cassandra-1/data:/var/lib/cassandra
      - ${PWD}/config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - portainer

  cassandra-2:
    image: cassandra:latest
    container_name: cassandra-2
    restart: on-failure
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_SEEDS=cassandra-1, cassandra-2, cassandra-3
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - ${DATA}/cassandra-1/data:/var/lib/cassandra
      - ${PWD}/config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - portainer

  cassandra-3:
    image: cassandra:latest
    container_name: cassandra-3
    restart: on-failure
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_SEEDS=cassandra-1, cassandra-2, cassandra-3
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - ${DATA}/cassandra-1/data:/var/lib/cassandra
      - ${PWD}/config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
